name: Auto Generate PHP README

on:
  push:
    branches:
      - beta
    paths-ignore:
      - README.md

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Generate README Markdown
        run: |
          pip install readmeai
          readmeai --repository https://github.com/laikait/laika-route --output README.md

      - name: Commit and Push README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: auto-update PHP README [skip ci]" || exit 0
          git push